# Set up the prompt

autoload -Uz promptinit
promptinit
prompt mine

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# alias

alias ls='ls -F --color=auto' 
alias ll='ls -lh'
alias grep='grep --color=auto' 

# end alias

# variables

export PSQL_EDITOR='vim +"set syntax=sql" '

# end variables
